# Check out https://pre-commit.com/ for documentation
minimum_pre_commit_version: 3.3.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-symlinks
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.2
    hooks:
      - id: commitizen
        stages: ["commit-msg"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        stages: [commit]
        exclude: ^recipes/.*
